### ISSUE TITLE
Bug with nutritional value in recipes

### ISSUE THREAD

**Issue by Aleksander1Byte** [vasil1y-777/FooDate#92]
# When changing nutritional value from **_kilocalories_** to **_kilojoules_**, the value does not change
![image](https://user-images.githubusercontent.com/94600445/200170320-cd75e3f1-fcfb-4439-9492-e4802b4f2ce0.png)

![image](https://user-images.githubusercontent.com/94600445/200170344-213c98af-91d2-4a80-861a-c5629a913e59.png)

### This thing is in production.

**Comment by vasil1y-777** [comment]
Please, send you browser console screenshot. It works for me. Problem is in you Javascript

**Comment by Aleksander1Byte** [comment]
![image](https://user-images.githubusercontent.com/94600445/200265424-9c7b1d00-56a2-4807-872f-27dd5d926734.png)
I use Opera GX. I don't think the problem is with runtime.lastError. I tried another internet browser (edge), also not working
I checked if this bug was happening on my mobile phone and it was
